# Generated by Django 4.2.1 on 2026-02-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id_status", models.AutoField(primary_key=True, serialize=False)),
                ("nama_status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                ("id_produk", models.AutoField(primary_key=True, serialize=False)),
                ("nama_produk", models.CharField(max_length=255)),
                ("harga", models.IntegerField()),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.kategori",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.status",
                    ),
                ),
            ],
        ),
    ]
